spring:
  application:
    name: product-service

  profiles:
    active: local

  config:
    import: "optional:configserver:http://localhost:8888"

  cloud:
    config:
      label: develop
      fail-fast: false

  main:
    allow-bean-definition-overriding: true

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
